# Generated by Django 3.0.5 on 2025-10-25 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 13, 48, 49, 382671)),
        ),
    ]
